#!/usr/bin/env python3

import sqlite3
from optparse import OptionParser

def main():
    parser = OptionParser()
    # <sql> <period> <unit> <target>
    parser.add_option('-c', dest='column_names', default='')
    (options, args) = parser.parse_args()

    columns = options.column_names.split(',')

    connection = sqlite3.connect('db.sqlite')
    connection.row_factory = sqlite3.Row
    c = connection.cursor()

    with open('targets.sql', 'r') as query:
        c.execute(query.read(), args[0:4])

        for row in c:
            if options.column_names:
                print(' '.join(str(row[i]) for i in columns))
            else:
                print(' '.join(str(i) for i in row))

if __name__ == "__main__":
    main()
